### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by FireEmerald** [DerNiccoo/MyFS#2]
**READ-ONLY Filesystem:**
- [x] Lesen einer existierenden Datei.
- [x] Buffer Struktur für das Lesen/Schreiben. @DerNiccoo 

**READ-WRITE Filesystem:**
- [ ] Neue Dateien erstellen.
- [ ] Existierende Dateien bearbeiten.
    - [ ] FuseWrite, zum (über-)schreiben in Dateien.
- [ ] Existierende Dateien löschen.
- [ ] Überprüfen der Rechte einer Datei.
- [ ] SuperBlock füllen und Rechte aus den SuperBlock nehmen um diese für FuseGetAttr() bei "/" zurück zu geben.
- [ ] SuperBlock automatisch beim Hinzufügen/Löschen/Ändern von Daten aktualisieren.
- [ ] Dafür sorgen das der Container groß genug ist. Max? @thma1023 
- [ ] Sinnvolle ERROR Returns.

**Bugs:**
- [ ] Berechnung der Positionen der START/END Blöcke.
- [ ] ~~Beim erstellen einer neuen Datei wird ein Ordner erstellt. Keine normale Datei.~~
- [x] Nach dem Löschen einer Datei, können die restlichen nicht mehr geöffnet werden.

**Fragen:**
- [ ] Wollen wir den Container umschreiben, zum verwalten der freien Blöcke oder lassen wir es so wie es ist. Nachteil wäre das wir alle Blöcke durchgehen zum finden von freien Blöcken.
